libc_a_SOURCES += \
	%D%/memcmp-stub.c %D%/memchr-stub.c \
	%D%/memchr.S %D%/memcmp.S %D%/memmove.S %D%/memmove-stub.c %D%/memset.S %D%/memcpy-asm.S %D%/memcpy.c %D%/strlen.c \
	%D%/strcpy.c %D%/strcmp.S %D%/setjmp.S %D%/ieeefp.c %D%/ffs.c
